export const PRIMARY_COLOR="#7743DB"
export const SECONDARY_COLOR="#FFE9B1"
export const DARK_COLOR="#3B3486"
export const LIGHT_COLOR="#FCFDF2"
export const THIRD_COLOR="#A7A7A7"
export const THIRD_LIGTH_COLOR="#8F8B8B2D"
