import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {DARK_COLOR, LIGHT_COLOR, PRIMARY_COLOR} from '../../utils/constants';

const styles = StyleSheet.create({
  infoDayContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: '100%',
    backgroundColor: ' red',
  },
  toolsContainer: {
    flex: 1,
    padding: 5,
    marginVertical: 5,
    minHeight: 80,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
  },
  rowEvenly: {
    width: '100%',
    paddingHorizontal: 4,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  around: {
    justifyContent: 'space-around',
    paddingHorizontal: 0,
    alignSelf: 'center',
  },
  titleBtn: {
    color: DARK_COLOR,
    fontWeight: 'bold',
    padding: 5,
  },
  container_day: {
    width: '12.5%',
    height: 48,
    borderColor: PRIMARY_COLOR,
    borderWidth: 1,
    borderRadius: 5,
    margin: 2,
  },
  text_day: {
    fontSize: 12,
    color: DARK_COLOR,
    fontFamily: 'Poppins-Regular',
    textAlign: 'left',
    paddingLeft: 3,
    alignSelf: 'flex-start',
  },
  text_today: {
    fontSize: 8,
    fontFamily: 'Poppins-Bold',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: LIGHT_COLOR,
  },
  today: {
    backgroundColor: DARK_COLOR,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    alignSelf: 'flex-end',
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: '30%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  text_week: {
    fontSize: 14,
    color: DARK_COLOR,
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
  },
  container_body: {
    flexDirection: 'column',
    justifyContent: 'space-around',
    width: wp('98%'),
    alignSelf: 'center',
  },
  headerPageContainer: {
    width: wp('100%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerPageTitle: {
    fontSize: 28,
    fontFamily: 'Poppins-Bold',
    color: LIGHT_COLOR,
    textShadowColor: PRIMARY_COLOR,
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 1,
  },
  control_month_container: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 'auto',
    padding: 5,
    backgroundColor: DARK_COLOR,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    alignItems: 'center',
  },
  control_month_text: {
    fontSize: 24,
    paddingTop: 2,
    color: LIGHT_COLOR,
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
  },
  container_calendar: {
    flex: 1,
    padding: 5,
    paddingBottom: 8,
    borderWidth: 3,
    borderColor: DARK_COLOR,
    elevation: 4,
    backgroundColor: LIGHT_COLOR,
    borderBottomLeftRadius: 7,
    borderBottomRightRadius: 7,
  },
});
export default styles;
